# This is a basic workflow to help you get started with Actions

name: DockerDelphiCompile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    freeupspace:
        name: Build my artifact
        runs-on: ubuntu-latest
        steps:
          - name: Before
            run: |
              echo "Free space:"
              df -h
          - name: Maximize build space
            uses: easimon/maximize-build-space@master
            with:
              root-reserve-mb: 512
              swap-size-mb: 1024
              remove-dotnet: 'true'
              remove-android: 'true'
              remove-haskell: 'true'
              remove-codeql: 'true'
              remove-docker-images: 'true'
          - name: After
            run: |
              echo "Free space:"
              df -h
    docker:
        runs-on: ubuntu-20.04
        needs: [freeupspace]
        container:
          image: lmbelo/d4d:0.0.1-alpha
          options: --user root
          credentials:
            username: lmbelo
            password: ${{ secrets.docker_hub_password}}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: super-step
              shell: bash
              run: |
                echo "$(ls -a)"
