# This is a basic workflow to help you get started with Actions

name: DockerDelphiCompile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:    
    delphi4docker:
        runs-on: ubuntu-20.04
        #needs: [freeupspace]
        steps:
          - name: Free Disk Space (Ubuntu)
            uses: jlumbroso/free-disk-space@main
            with:
              # this might remove tools that are actually needed,
              # when set to "true" but frees about 6 GB
              tool-cache: true
          - name: Login to Docker Hub
            uses: docker/login-action@v2.1.0
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              logout: true
          - name: Push Docker image
            run: |
              pwd
              docker pull lmbelo/d4d:0.0.1-alpha
              docker run --rm -it d4d
        #container:
        #  image: lmbelo/d4d:0.0.1-alpha
        #  options: --user root
        #  credentials:
        #    username: lmbelo
        #    password: ${{ secrets.docker_hub_password}}
        #steps:
        #    - name: Checkout repository
        #      uses: actions/checkout@v2
        #    - name: super-step
        #      shell: bash
        #      run: |
        #        echo "$(ls -a)"
