# This is a basic workflow to help you get started with Actions

name: DockerDelphiCompile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:    
    delphi4docker:
        runs-on: ubuntu-20.04      
        steps:
          - name: Free Disk Space
            uses: jlumbroso/free-disk-space@main
            with:
              # this might remove tools that are actually needed,
              # when set to "true" but frees about 6 GB
              tool-cache: true
          - name: Checkout main repo
            uses: actions/checkout@v2
          - name: Login to Docker Hub
            uses: docker/login-action@v2.1.0
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
              #logout: true
          - name: Push Docker image
            run: |
              docker pull lmbelo/d4d:0.0.1-alpha
          - name: Run Docker container
            run: |
              cat > $(pwd)/test/TestApp1/compile.bat <<EOF            
              msbuild TestApp1.dproj /t:Clean /t:Build /p:Config=Release /p:Platform=Win32
              msbuild TestApp1.dproj /t:Clean /t:Build /p:Config=Release /p:Platform=Win64
              EOF
            
              ls -a
            
              docker run -d -v $(pwd)/test/TestApp1:/root/.wine/drive_c/users/root/Documents/Embarcadero/Studio/Projects/Shared --name d4d lmbelo/d4d:0.0.1-alpha
              docker exec -i d4d "wine cmd /C msbuildconfig.bat /C Shared\compile.bat"
              
              ls -a
